version: '1.0.0'
services:
  postgres:
    image: postgres:13.4
    container_name: vwdb
    environment:
      POSTGRES_DB: vwdb
      POSTGRES_USER: waf
      POSTGRES_PASSWORD: vwzhsha3
    command: postgres -c listen_addresses=*
    ports:
      - 3306:5432
