server:
  servlet:
    context-path: /api/

#springdoc:
#  swagger-ui:
#    url: /swagger.yaml

spring:

# Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:3306}/${DB_NAME:vwdb}
    username: ${DB_USER:waf}
    password: ${DB_PASSWORD:vwzhsha3}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE