spring:

# Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

# JPA
  jpa:
    hibernate:
      ddl-auto: update