# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: VW CI with Gradle

on:
  push:
    branches:
      - 'main'   # includes main
  pull_request:
    branches:
      - '**'      # matches every branch
      - '!main'   # excludes main

env:
  DB_URL: localhost:3306
  DB_NAME: vwdb
  DB_USER: root
  DB_PASSWORD: vwzhsha3

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: ${{ env.DB_NAME }}
        mysql root password: ${{ env.DB_PASSWORD }}

    - name: Grant access to execute gradlew
      run: chmod +x ./gradlew

    - name: Execute gradlew build task
      run: ./gradlew build
